development:
  secret_key_base: 87bb23acfeae202d89cf22f5219a293b8c9f3508bbaadaa7e99ef35316a86facdc8248ca69464bb5098473c541400d8261f490ca1785d3a893f223f3834b8f5b
  twilio_account_sid: 'AC1c2309bed1816eaf4e034ad4c3c0a728'
  twilio_auth_token: 'd2e17824212306863107a05819edc5e6'
  RECAPTCHA_SITE_KEY: '6Lf71G0UAAAAAJhuGjErePUyNoJ7dx79tKDn4lJn'
  RECAPTCHA_PRIVATE_KEY: '6Lf71G0UAAAAAJDJBKUdsp9RAl6HRmTSGdcE4iQZ'
  MAINSMS_PROJECT: 'amigorent'
  MAINSMS_KEY: 'd9264f919e311'

test:
  secret_key_base: 5e7f770c143653e40361597734d925699102a59775c05100b0ebab802db1a004283dabb1d009b5c5d32791aa35cbeb17ea89c6b14016cbada1b70d5af1502c42
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  RECAPTCHA_SITE_KEY: '6Lf71G0UAAAAAJhuGjErePUyNoJ7dx79tKDn4lJn'
  RECAPTCHA_PRIVATE_KEY: '6Lf71G0UAAAAAJDJBKUdsp9RAl6HRmTSGdcE4iQZ'
  MAINSMS_PROJECT: 'amigorent'
  MAINSMS_KEY: 'd9264f919e311'
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  RECAPTCHA_SITE_KEY: '6LcVT0gUAAAAAPKZE3lBmeLzPmzMigiaHIsIknfF'
  RECAPTCHA_PRIVATE_KEY: '6LcVT0gUAAAAALS5AUETxGdAIp8ZtMyfn7B1Nlhv'
  MAINSMS_PROJECT: 'amigorent'
  MAINSMS_KEY: 'd9264f919e311'
